from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('autorzy/', views.autorzy_list),
    path('autorzy/<int:pk>/', views.autorzy_detail),
    path('autorzy/search/<str:string>/', views.autorzy_string),
    path('autorzy/update/<int:pk>/', views.autorzy_update_delete),
    path('autorzy/delete/<int:pk>/', views.autorzy_update_delete),
    path('autorzy/post/', views.autorzy_post),
    path('gatunki/', views.gatunki_list),
    path('gatunki/<int:pk>/', views.gatunki_detail),
    path('gatunki/update/<int:pk>/', views.gatunki_update_delete),
    path('gatunki/delete/<int:pk>/', views.gatunki_update_delete),
    path('gatunki/post/', views.gatunki_post),
    path('books/', views.books_list),
    path('books/<int:pk>/', views.books_detail),
    path('books/autor/<str:string>/', views.books_autor),
    path('books/nazwa/<str:string>/', views.books_string),
    path('books/gatunek/<str:string>/', views.books_gatunek),
    path('books/update/<int:pk>/', views.books_update_delete),
    path('books/delete/<int:pk>/', views.books_update_delete),
    path('books/post/', views.books_post),
    path('borrows/', views.borrows_list),
    path('borrows/<int:pk>/', views.borrows_detail),
    path('borrows/konto/<str:string>/', views.borrows_konto),
    path('borrows/update/<int:pk>', views.borrows_update_delete),
    path('borrows/delete/<int:pk>', views.borrows_update_delete),
    path('borrows/post/', views.borrows_post),
    path('active/', views.borrows_active),
    path('login/', include('rest_framework.urls'), ),
    path('register/', views.sign_up),
]
