# Generated by Django 4.2.6 on 2023-10-23 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_osoba_stanowisko_delete_testclass_osoba_stanowisko'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=datetime.date(2023, 10, 23)),
        ),
    ]
