# Generated by Django 4.2.6 on 2023-10-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_osoba_data_dodania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='data_dodania',
        ),
    ]
