# Generated by Django 4.2.6 on 2023-11-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'verbose_name_plural': 'osoby'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'verbose_name_plural': 'stanowiska'},
        ),
    ]
