# Generated by Django 4.2.6 on 2023-11-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_alter_osoba_options_alter_stanowisko_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='Osoba', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
