# Generated by Django 4.2.6 on 2023-11-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_osoba_wlasciciel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='wlasciciel',
        ),
    ]
