# Generated by Django 4.2.6 on 2023-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='data_zwrotu',
            field=models.DateField(blank=True),
        ),
    ]
