# Generated by Django 4.2.6 on 2023-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektApp', '0002_alter_borrow_data_zwrotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='data_zwrotu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
